#! /bin/sh

### BEGIN INIT INFO
# Provides:          dhcpmon
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of dhcpmon
# Description:       starts instance of dhcpmon
### END INIT INFO

############### EDIT ME ##################

#APP_PATH=""

# path to daemon
DAEMON=/usr/sbin/tcpdump

# startup args
DAEMON_OPTS="-ilan0 -C10000000 -w/tmp/dhcp.cap -s0 -p udp portrange 67-68"

# script name
NAME=dhcpmon

# app name
DESC=dhcpmon

RUN_AS=root

PID_FILE=/var/run/dhcpmon.pid

############### END EDIT ME ##################

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $NAME: "

        start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile -a $DAEMON -- $DAEMON_OPTS

	if [ $? ]; then
	    echo "[OK]"
	else
	    echo "[FAILED]"
	fi

        ;;
  stop)
        echo -n "Stopping $NAME: "
        start-stop-daemon --stop --pidfile $PID_FILE
	if [ $? ]; then
	    echo "[OK]"
	else
	    echo "[FAILED]"
	fi
        ;;

  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --pidfile $PID_FILE
        sleep 1
        start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile -a $DAEMON -- $DAEMON_OPTS
	if [ $? ]; then
	    echo "[OK]"
	else
	    echo "[FAILED]"
	fi

        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
